---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
  namespace: default
  labels:
    app: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      namespace: default
      labels:
        app: workload
    spec:
      serviceAccountName: workload
      containers:
      - name: workload
        image: spire-workload:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spire-agent-socket/agent.sock
      volumes:
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
